spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: validate
    show-sql: false
    properties.hibernate.format_sql: true

  flyway:
    enabled: true
    locations: 
      - classpath:db/migration
    baseline-on-migrate: true
    
  h2:
    console:
      enabled: true
      path: /h2-console

management.endpoints.web.exposure.include: info,health,flyway